# Generated by Django 6.0.7 on 2026-07-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="duration",
            field=models.PositiveIntegerField(
                default=60, help_text="Duration in minutes"
            ),
            preserve_default=False,
        ),
    ]
