# Generated by Django 6.0.7 on 2026-07-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_plan_duration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Holiday",
        ),
    ]
