# Generated by Django 6.0.7 on 2026-07-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_delete_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="order_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
