# Generated by Django 6.0.7 on 2026-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_slots",
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="plan",
            name="weekly_slots",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
