# Generated by Django 6.0.7 on 2026-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_order_id_booking_payment_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("public", "Public Holiday"),
                            ("festival", "Festival"),
                            ("ekadashi", "Ekadashi"),
                            ("vrat", "Vrat"),
                        ],
                        default="festival",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="order_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
