# Generated by Django 6.0.7 on 2026-07-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_holiday_alter_booking_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="date",
            field=models.DateField(),
        ),
    ]
