# Generated by Django 6.0.7 on 2026-07-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_userpass_delete_pass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="price",
        ),
        migrations.AddField(
            model_name="plan",
            name="monthly_price",
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="session_price",
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
            preserve_default=False,
        ),
    ]
